apiVersion: batch/v1
kind: Job
metadata:
  name: database
  namespace: microservice
  annotations:
    author: "Mahmoud Abd Alziem"
spec:
  template:
    spec:
      containers:
      - name: database
        image: node:16
        command: ["npm","start"]
        resources: {}
      restartPolicy: Never
  backoffLimit: 4