apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: microservice
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - name: database
      protocol: TCP
      port: 3005
      targetPort: 3005
